version: '3.9'
services:
  java_db12:
    container_name: java_db12
    image: postgres:12
    ports:
      - "5436:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 352800
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
# docker compose up -d java_db
# docker-compose ps
